// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlzvghpfdohkwazlvta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubHp2Z2hwZmRvaGt3YXpsdnRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTk1OTYsImV4cCI6MjA2OTEzNTU5Nn0.MgM7BFlJfXKV9ArVivFF57IV8Lo4o9HnR7lJTrFnDbY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});